# -*- coding: utf-8 -*-
"""Anova_test(stats).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZKZYwpjGHU0u2FsYohPPxG2wJ0YvZHk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# defining the null and alternative hypothesis
# Null hypothesis(H0): There is no significant difference between means of  the 3 groups
# Alternative hypothesis: There is a significant difference between means of the 3 groups
np.random.seed(101)
# generating random numbers for control group
control_yield = np.random.normal(loc = 30 ,scale = 5 , size = 50)
Fertilizer_x_yield = np.random.normal(loc = 38 , scale = 6,size = 50)
Fertilizer_y_yield = np.random.normal(loc = 45 ,scale = 7, size = 50)

df = pd.DataFrame({
                   'Treatment':['control'] * 50 + ['Fertilizer_x'] *50 +['Fertilizer_y'] *50,# creates a list of control word repeated for 50 times
                  'yield':np.concatenate([control_yield,Fertilizer_x_yield,Fertilizer_y_yield]) # Joining three variables which are having a list of 50 numbers


})


df

print('Statistics:')
print(df.groupby('Treatment')['yield'].describe()) # joining treatment and yield to get their individual statistics

plt.figure(figsize = (10,7))
sns.violinplot(x = 'Treatment',y = 'yield',data =df ,palette = 'viridis')
plt.title("Yield distributions")
plt.show()

import scipy.stats as stats
#Checking the assumptions of Anova test
# 1.Normality(Normal distribution)
for treatment in ['control','Fertilizer_x','Fertilizer_y']:
  shapiro_stat,shapiro_p = stats.shapiro(df[df['Treatment'] == treatment]['yield']) # storing p_value as shapiro_p and test stat as shapiro_stat
  print(f'Treatment:{treatment}')
  print(f'shapiro_stat:{shapiro_stat:.2f}')
  print(f'shapiro_p:{shapiro_p:.2f}')

if shapiro_p > 0.05:    # if shapiro_p is greater than alpha value then it is normal distribution otherwise not.
  print('The data is normally distributed')
else:
  print('The data does not follow normal distribution')

# 2.Homogeneity of Variances (Equal Variance) # levene_stat is used to test whether the variances are equal or not
levene_stat,levene_p = stats.levene(df[df['Treatment'] == 'control']['yield'],
                                    df[df['Treatment'] == 'Fertilizer_x']['yield'],
                                    df[df['Treatment'] == 'Fertilizer_y']['yield']
                                    ) # This will match the yield with treatment column to get all the rows of control yield
print(f'levene_stat:{levene_stat}')
print(f'levene_p:{levene_p:.2f}')

# Comparing p_value with alpha
if levene_p > 0.05:
  print('The groups have equal variance ')    # variance is the spread of the data. whether the data points are are narrowly arranged or widely arranged.
else:
  print('The group does not have equal variance')

#Obtaining value of  f_statistic
f_statistic,p_value = stats.f_oneway(
                                      df[df['Treatment'] == 'control']['yield'],
                                        df[df['Treatment']== 'Fertilizer_x']['yield'],
                                         df[df['Treatment'] == 'Fertilizer_y']['yield']
                                      )

# Obtaining f_critical value
alpha = 0.05
#df_numerator = k -1, k = total no of groups
# df_denominator = N-1,N = total no of samples,we have 150 samples.
dfn = 2 # 3-1
dfd =147 # N - k
f_critical_val = stats.f.ppf(1-alpha,dfn,dfd)

# Comparing F-statistic and f-critical_value
print(f'f_statistic value:{f_statistic:.2f}')
print(f'critical value at alpha {alpha}:{f_critical_val:.2f}')

if f_statistic > f_critical_val:
  print('Rejecting the null hypothesis, That means the grps are significantly different ')
else:
  print('Failing to reject the null hypothesis')

# Performing post hoc test(tukey_hsd) to determine which exact grps are different from each other
from statsmodels.stats.multicomp import pairwise_tukeyhsd   #pairwise tukey is the function we are using, importing from statsmodels.stats.multicomp

tukey_results = pairwise_tukeyhsd(endog = df['yield'], groups = df['Treatment'],alpha = 0.05) # endog means endogenous that means the dependent variable,groups is the independent variable that we are giving to compare the 3 groups
print(tukey_results)                                                                          # alpha is significance level.

"""In tukeyhsd hsd is the honest significance difference
p-adj is the p_value for both the grps if p-adj is  less than the alpha then there is a significance difference between the grps.
C  
"""

# Visulaizing the Results through boxplot
import matplotlib.pyplot as plt
import seaborn as sns

# Creating the boxplot
plt.figure(figsize=(10, 7))
sns.boxplot(x='Treatment', y='yield', data=df, palette='viridis')

plt.title('Comparison of Crop Yield by Fertilizer Treatment', fontsize=16)
plt.xlabel('Fertilizer Treatment', fontsize=12)
plt.ylabel('Yield (in bushels per acre)', fontsize=12)
plt.show()

"""Conclusion:
           An analysis was conducted to determine if different fertilizer treatments have a statistically significant effect on crop yield.

A One-Way ANOVA test was performed, and the results were significant (F-statistic = 67.97, p-value = 0.00), leading to the rejection of the null hypothesis. This indicates that there is a significant difference in the average yields among the three treatment groups (control, Fertilizer_x, Fertilizer_y).

To identify which specific groups differed, a Tukey HSD post-hoc test was conducted. The results confirmed that all three groups were significantly different from one another. Based on the mean differences, the performance can be ranked as: Fertilizer_y > Fertilizer_x > control. Therefore, Fertilizer_y is the most effective treatment for increasing crop yield.


"""