# -*- coding: utf-8 -*-
"""chisquare_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXW8ON2G3wFe2ki4Eq_cOeyKJJldg2u4

Chi Square Test: A chi square test in statistics is used to determine the relation between two categorical variables.
Problem Statement: A mizzare corporation has collected a data that contains device type and customer satisfaction level.There motive is to find whether there is a relation between device type and the customer satisfaction level which is achieved by chi square test.
"""

# Null hypothesis(H0):There is no relation between two variables Customer satisfaction level and device type  are independent
# Alternative Hypothesis(H1):There is a relation between Customer satisfaction level and device type
import pandas as pd
from scipy.stats import chi2_contingency
# Loading the data
data = [[50,70],
        [80,100],
        [60,90],
        [30,50],
        [20,50]]
observed_df = pd.DataFrame(data, columns = ['Smart thermostat','Smartlight'],index=['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied'])

observed_df

observed_df.dtypes

chi2, p_value, dof, expected = chi2_contingency(observed_df.values) # Converting df into numpy array as function requires numerical data
print(f'expected: \n {expected}')
expected_df = pd.DataFrame(expected, columns = ['Smart thermostat','Smartlight'],index=['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied'])
print(expected_df)

print(f'chi2:{chi2},p_value:{p_value},dof:{dof},\nexpected:\n{expected}')

# critical value
alpha = 0.05
from scipy.stats import chi2
critical_value = chi2.ppf(1-alpha,dof)
critical_value

print(f'P_value: {p_value}')
print(f'alpha value: {alpha}')
if p_value > alpha:
  print('Accept Null hypothesis,that means Customer satisfaction level and device type  are independent ')

else:
  print('Reject null hypothesis,that means customer satisfaction level and device type are dependent to each other')

"""Conclusion:We can conclude that there is no significant relation between customer satisfaction level and the device type Used."""

