# -*- coding: utf-8 -*-
"""Hypothesis_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyM6_fBVaorY1aI5GZFB6tXiNkZCZDDB

A bombay hospitality ltd has came up with a formula that calculates weekly operating costs of the restaurants.Formula: w = 1000 + 5 * x
Finding whether the claim of restaurents who are saying the weekly operating is  4000 is True or false using hypothesis testing.
"""

import math
from scipy.stats import norm

# null hypothesis:no significant difference model is True
# Alterative hypothesis(H1): There is a significant difference and the claim is False

# Defining the values
sample_mean = 3050
model_mean = 4000 # operating cost  given by formula.when units = 600 w = 1000 +5 * 600 = 4000
n = 25 # sample size: 25 restaurants
std_dev  = 125 # 5 * 25 , 5 is cost per one unit
alpha = 0.05

# calculating standard error
std_error = std_dev /math.sqrt(n)
std_error

# Calculating Z-score value
z_score = (sample_mean-model_mean) / std_error
z_score

# calculating Z_critical_value
z_critical_value = norm.ppf(alpha)
print( f' z_critical value at alpha = 0.05:{z_critical_value:.3f}')

# Decision
if z_score > z_critical_value:
  print('accept null hypothesis, that means there is no significant deference and the claim is true')
else:
  print('Reject null hypothesis, that means there is a significant difference and claim is False')

"""The formula given by bombay hospitality is wrong in producing the actual weekly operating cost.So the claim is wrong the operating cost is lower than the 4000 rs which is claimed by the bombay hospitality."""